### ISSUE TITLE
Found something that isn't working

### ISSUE THREAD

**Issue by ghost** [subliun/toxme#11]
Hello, i was using the website and i found some bugs:
1) if i try to add twyz@toxme.io in the qtox client it says "This Tox ID does not exist"
2) if i try click "Click here to add twyz." in https://toxme.io/u/twyz it says "75A1247A75D68660A1A889730030438FCA0BB8AADB3A75960EBC5FAE210235C1FC2B0D96A1 is not a valid Tox address."
the first 2 numbers are missing, because my Tox ID is 
6875A1247A75D68660A1A889730030438FCA0BB8AADB3A75960EBC5FAE210235C1FC2B0D96A1

**Comment by subliun** [comment]
Works in uTox 0.4.4
I suggest opening a bug in the qTox repo. https://github.com/tux3/qTox
