### ISSUE TITLE
HTTPS API questions

### ISSUE THREAD

**Issue by nurupo** [subliun/toxme#12]
As far as I know, you want the https API to be a standard other services like toxme implement.

I have a few questions on the current API standard:
1. Tox user owns example.org and wants to be able to run a toxme-like service with the https API, so that name@example.org would get resolved to a tox id. Your API specification says that the API for name@example.org should be made available at example.org/api, but what if the Tox user already hosts something at example.org (e.g. a blog) or what if /api is already being used by something else, then what should the Tox user do?
2. Why instead of using named paths and post/get/put/delete/etc requests (RESTful API) it's just a single /api with the actual actions being encoded as numbers in the payload? I'm a bit far from webdev, but I haven't seen services providing such apis with action codes in the payload.
3. Where is the API versioning information? What will you do if the API standard gets updated?

I think that all of these 3 questions could be resolved by using something like "toxapi.example.org/1/" as API endpoint  ("1" is the API version) and RESTful API for the entire thing. ("toxapi" is too general though, something specific to the Tox name resolving service should be used instead.) You can see http://api.imgur.com/ for an example of this.

**Comment by benwaffle** [comment]
Also it might be nice if the error codes were strings. i18n could be implement using `Content-Language` header or on the client

**Comment by Zer0-One** [comment]
:+1:  very valid questions

**Comment by subliun** [comment]
1. They should not host a toxme instance
2. I'm not maintaining toxme
3. What will toxcore do if the api standard gets updated?

I accept pull requests.

**Comment by alexbakker** [comment]
@subliun 
Tell me, why are we switching to toxme's API if the only one hosting an instance of it is not willing to maintain it?

**Comment by Diadlo** [comment]
@Impyy Not "switch" just support too

**Comment by alexbakker** [comment]
@Diadlo 
Yes, "switch".
The goal is to get rid of toxdns entirely.

**Comment by Diadlo** [comment]
@Impyy Not now

**Comment by optimumtact** [comment]
@Impyy because the only other name site is utox.org

**Comment by alexbakker** [comment]
@Diadlo Yes now. Subliun has already disabled toxdns on toxme.io.

**Comment by Diadlo** [comment]
@Impyy Yes, toxdns on toxme.io already disabled, but qTox still use toxdns and (may be will support toxme)

**Comment by subliun** [comment]
@Impyy because it's better than toxdns.

**Comment by cebe** [comment]
> what if /api is already being used by something else, then what should the Tox user do?

I think a good idea would be to use [SRV Records](https://en.wikipedia.org/wiki/SRV_record) in DNS to provide information about where to find the toxdns server for a domain.

An example entry could look like this:

```
_toxdns._tcp.toxme.io. 3600 IN SRV 0 1 80 api.toxme.io
```

A client will make a DNS query to obtain the information that the toxdns api for this domain can be found on port 80 on the server with address `api.toxme.io`.

**Comment by subliun** [comment]
@nurupo I'll fix #3. #1 I'm a bit iffy about. #2 I won't fix.

**Comment by cebe** [comment]
@subliun care to explain the decision?

**Comment by subliun** [comment]
@cebe no one has convinced me (or even attempted to, for that matter) the benefits of switching to a RESTful api over what we have currently. #1 because any solution has similar problems as just using /api, though I'm not sure about this one.

**Comment by cebe** [comment]
`#1` could be fixed by using SRV records. what do you think? Would allow people to use their own domain for tox names regardless of whats running on it already.

**Comment by subliun** [comment]
SRV records sound like a good solution, but also would be annoying to implement.

**Comment by benwaffle** [comment]
@subliun using REST adds support for libraries such as [retrofit](https://square.github.io/retrofit/)

**Comment by subliun** [comment]
@nurupo could you open separate issues for 1 and 3?

**Comment by nurupo** [comment]
So, I have tried to make my version of the HTTPS API standard for name-based Tox Id lookups. This is what I have came up with: https://gist.github.com/nurupo/644c22e17b9b4643f103

Please direct the comments to #tox-dev IRC channel, not to this GitHub Issue.

As a few differences with subliun's API that I can list of top of my head:
- Formally defines `name` part of `name@example.com`
- Uses SRV DNS record to find host address on which the API is running
- Uses API versioning
- Tries to be as RESTful as possible given security requirements
- Extra paranoid about security: even if SSL/TLS is HTTPS is broken, it tries it best not to leak which names people are looking up
-  Allows to create/update/delete name to Tox Id mappings without any passwords, by using the keypair associated with Tox Id to encrypt things as a proof
  - Removes the need for passwords
  - Allows clients to integrate automatic creation/updation/deletion of name to Tox Id mappings as there is API for that
- Uses client and server nonces to defeat reply attacks by both parties
- No random "bio" information or anything like that in the API as it's not tied with how toxme.io works, it's supposed to be general API
- Has better documentation, with thread and trust models
- Many other things
