### ISSUE TITLE
Taking over toxme.io hosting

### ISSUE THREAD

**Issue by LittleVulpix** [subliun/toxme#16]
@subliun if you don't want to run the io host, I'd like to get in touch and take over.

Thanks!

**Comment by LittleVulpix** [comment]
@subliun I have the instance set up. Now all I need are the db and the domain.

**Comment by LittleVulpix** [comment]
@subliun I have it more or less set up, but I didn't manage to have both tornado and nginx in the secure mode. Nginx is secure and routing requests. Tornado isn't, because for some reason it wouldn't work when I configured proxy_pass to go to https. Not sure why, couldn't find any interesting logs. If you have any tips, let me know so I can get this working.

Also, what exactly is /pk ? I found one reference to it in readme, nothing else, and I see some 404s going to that.

**Comment by alexbakker** [comment]
/pk is used by toxdns clients to obtain the public key before sending a request. If you have the DNS functionality disabled, then it's not a problem that /pk returns a 404.

**Comment by LittleVulpix** [comment]
Yeah the dns functionality is disabled. Thanks @Impyy.

**Comment by LittleVulpix** [comment]
I'm guessing things are alright. If you can help me with the secure thing with nginx, that'd be nice, but since it's all going through nginx anyway, it shouldn't matter. Thanks @subliun !

**Comment by subliun** [comment]
You need to fix /pk otherwise Antox won't work

**Comment by LittleVulpix** [comment]
https://github.com/LittleVulpix/toxme/pull/2/commits "merged", now it's showing stuff. Though, it's still not letting clients search.

The exception you added is thrown in place of the actual error (from before). So what's the problem?

**Comment by LittleVulpix** [comment]
@subliun Antox is able to look up users. So is qtox. Couldn't get antox to register me, it said something like failed to load library so I don't know if it's a problem on toxme.io or antox's.

uTox cannot resolve any names though. 

EDIT: https://github.com/GrayHatter/uTox/issues/145 found it.

**Comment by LittleVulpix** [comment]
@subliun toxmeio handover finished, toxme.io running fine on the new location :)

**Comment by subliun** [comment]
Nice Work :)
